### ISSUE TITLE
Find proper sample video

### ISSUE THREAD

**Issue by AidasVaiksnoras** [AidasVaiksnoras/Foosball2text#10]
In video should be at least 3 goals.
Video projection should be from the top of the table.
Ball color should differ from table background color.

**Comment by WarHatch** [comment]
Kay, čia nevisai pagal reikalavimus, bet extra footage, jei norit pasibandyt
https://drive.google.com/drive/folders/0Bwn8a_ms2tkEUnJlWXI0Uk5GaFk?usp=sharing
