### ISSUE TITLE
Implement function which decides if goal was made

### ISSUE THREAD

**Issue by AidasVaiksnoras** [AidasVaiksnoras/Foosball2text#13]

**Comment by WarHatch** [comment]
Okay, mano įdėja tokia būtu:
- Yra nustatytos vartų zonos (kol kas pre-compile gal aprašyti jas reiktų) kairėje ir dešinėje video pusėje
- Jei kamuoliukas toje zonoje (peržengęs tą zoną?) dingsta kokiai gerai sekundei, tada skaičiuojamas įvartis

Thoughts?
