### ISSUE TITLE
One found object displayed ALWAYS

### ISSUE THREAD

**Issue by WarHatch** [AidasVaiksnoras/Foosball2text#26]
# In Ball.cs
```
        public void FindCordinates(Image<Gray, byte> frame)
        {
            CircleF[] circleArray = GetCirclesFromFrame(frame);
            if (circleArray.Length != 0) 
            {
                _circle = circleArray[circleArray.Length-1]; //<---- the issue
                x = _circle.Center.X;
                y = _circle.Center.Y;
            }
        }
```
We only get one circle from the Array even though there are possibly more of them

**Comment by mnaujokas** [comment]
There can only be one ball on the playing field thus we extract only one circle from the array. The Filter makes sure that there are no other recognizable circles, but the ball itself in the filteredImage.
However, some sort of validation could be implemented in this function.
